export default {
    CURRENCY_CHANGE: 'CURRENCY_CHANGE',
    FILTERS: 'FILTERS',
    CHECKED: 'CHECKED',
    CHECK_ALL: 'CHECK_ALL',
    CHECKED_TICKETS: 'CHECKED_TICKETS',
    MY_TICKETS: 'MY_TICKETS'
}